services:
  # API Gateway - Node.js Express
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MS_AUTENTICACAO_URL=http://ms-autenticacao:8080
      - MS_PACIENTE_URL=http://ms-paciente:8082
      - MS_CONSULTA_URL=http://ms-consulta:8083
      - JWT_SECRET=hospital_jwt_secret_2025
      - REDIS_URL=redis://redis-server:6379
      - CORS_ORIGINS=http://localhost:4200,http://frontend:4200
    depends_on:
      - redis
    networks:
      - hospital-net
    restart: unless-stopped

  # Redis for JWT blacklist and caching
  redis:
    image: redis:7-alpine
    container_name: hospital-redis
    # Remove external port mapping - only internal communication needed
    expose:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - hospital-net
    restart: unless-stopped

volumes:
  redis_data:

networks:
  hospital-net:
    external: true
    name: ms-autenticacao_hospital-net
