services:
  # API Gateway - Node.js Express
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MS_AUTENTICACAO_URL=http://ms-autenticacao:8081
      - MS_PACIENTE_URL=http://ms-paciente:8083
      - MS_CONSULTA_URL=http://ms-consulta:8080
      - JWT_SECRET=minhaChaveSecretaSuperSeguraParaJWT2025HospitalSystem
      - REDIS_URL=redis://redis-server:6379
      - CORS_ORIGIN=*
    depends_on:
      - redis
    networks:
      - hospital-net
    restart: unless-stopped

  # Redis for JWT blacklist and caching
  redis:
    image: redis:7-alpine
    container_name: hospital-redis
    # Remove external port mapping - only internal communication needed
    expose:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - hospital-net
    restart: unless-stopped

volumes:
  redis_data:

networks:
  hospital-net:
    external: true
    name: ms-autenticacao_hospital-net
