services:
  # Serviço do Microsserviço de Paciente
  ms-paciente:
    build: . # Onde o Dockerfile do ms-paciente está (diretório atual)
    container_name: ms-paciente-app
    ports:
      - "8083:8083" # Mapeia porta do host (8083) para a porta do contêiner (8083)
    environment: # Variáveis de ambiente para o contêiner
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-paciente-db:5432/hospital_paciente # O nome do host é o nome do serviço do banco de dados no docker-compose
      SPRING_DATASOURCE_USERNAME: dac
      SPRING_DATASOURCE_PASSWORD: 123
      JWT_SECRET: minhaChaveSecretaSuperSeguraParaJWT2025HospitalSystem # Importante: Mesma chave do MS Autenticacao
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET_KEY: minhaChaveSecretaSuperSeguraParaJWT2025HospitalSystem
      # Para o ambiente de produção, é altamente recomendável usar variáveis de ambiente ou um gerenciador de segredos para JWT_SECRET.
    depends_on: # Garante que os serviços dependentes iniciem primeiro.
      ms-paciente-db:
        condition: service_healthy # Espera o DB estar saudável
    networks:
      - hospital-net # Conecta à rede definida

  # Serviço do Banco de Dados PostgreSQL para Paciente
  ms-paciente-db:
    image: postgres:16-alpine # Imagem oficial do PostgreSQL
    container_name: ms-paciente-db
    environment:
      POSTGRES_DB: hospital_paciente
      POSTGRES_USER: dac
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432" # Porta para acesso externo (diferente do MS Autenticacao que usa 5432)
    volumes:
      - paciente_db_data:/var/lib/postgresql/data # Volume para persistir dados do PostgreSQL
    healthcheck: # Healthcheck para o Compose esperar que o DB esteja pronto antes de iniciar o ms-paciente
      test: ["CMD-SHELL", "pg_isready -U dac -d hospital_paciente"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s # Tempo para o contêiner iniciar antes de começar a testar
    networks:
      - hospital-net

volumes:
  paciente_db_data: # Define o volume nomeado para persistência do DB

networks:
  hospital-net: # Define uma rede interna para os contêineres se comunicarem
    driver: bridge